/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab9p2_cesarnunez_juanmolina;

/**
 *
 * @author Hwan
 */
public class jf_examen extends javax.swing.JFrame {

    private alumno usuarioExamen = new alumno();
    public jf_examen() {
        initComponents();
        
        for (clase temp : usuarioExamen.getClases()) {
            clasesCombo.addItem(temp.getNombreClase());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tiempoLabel = new javax.swing.JLabel();
        notificacionLabel = new javax.swing.JLabel();
        clasesCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        seleccionarClase = new javax.swing.JButton();
        examenCombo = new javax.swing.JComboBox<>();
        seleccionarExamen = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tiempo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 50, -1, -1));
        getContentPane().add(tiempoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 80, 20));
        getContentPane().add(notificacionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 210, 20));

        clasesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        clasesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasesComboActionPerformed(evt);
            }
        });
        getContentPane().add(clasesCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 150, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("EXAMEN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 160, 40));

        seleccionarClase.setText("SELECCIONAR");
        seleccionarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarClaseActionPerformed(evt);
            }
        });
        getContentPane().add(seleccionarClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        examenCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        getContentPane().add(examenCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, -1));

        seleccionarExamen.setText("SELECCIONAR");
        seleccionarExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarExamenActionPerformed(evt);
            }
        });
        getContentPane().add(seleccionarExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clasesComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasesComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clasesComboActionPerformed

    private clase tempClase = new clase();
    private void seleccionarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarClaseActionPerformed
        for (clase temp : usuarioExamen.getClases()) {
            if(clasesCombo.getSelectedItem() == temp.getNombreClase()){
                tempClase = usuarioExamen.getClases().get(usuarioExamen.getClases().indexOf(temp));
                break;
            }
        }
        
        for (examen temp : tempClase.getExamenes()) {
            examenCombo.addItem(Integer.parseInt(temp.getIdExamen()));
        }
    }//GEN-LAST:event_seleccionarClaseActionPerformed

    private void seleccionarExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarExamenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarExamenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jf_examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jf_examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jf_examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jf_examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jf_examen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> clasesCombo;
    private javax.swing.JComboBox<String> examenCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel notificacionLabel;
    private javax.swing.JButton seleccionarClase;
    private javax.swing.JToggleButton seleccionarExamen;
    private javax.swing.JLabel tiempoLabel;
    // End of variables declaration//GEN-END:variables

    public void jf_examen(alumno temp ){
        this.usuarioExamen = temp;
    }
}
