/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab9p2_cesarnunez_juanmolina;

/**
 *
 * @author cesar
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_registro1 = new javax.swing.JFrame();
        jb_registrarse1 = new javax.swing.JButton();
        jtf_confirmarContrasenia1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jtf_contraseniaRegistro1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jtf_usuarioRegistro1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jtf_nombreRegistro1 = new javax.swing.JTextField();
        jl_bg4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jf_login2 = new javax.swing.JFrame();
        jb_registro2 = new javax.swing.JButton();
        jb_ingresar2 = new javax.swing.JButton();
        jl_bg5 = new javax.swing.JLabel();
        jtf_contraseniaLogin2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jtf_usuarioLogin2 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        jb_registrarse1.setBackground(new java.awt.Color(169, 169, 169));
        jb_registrarse1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb_registrarse1.setForeground(new java.awt.Color(51, 51, 51));
        jb_registrarse1.setText("Registrarse");
        jf_registro1.getContentPane().add(jb_registrarse1, java.awt.BorderLayout.CENTER);

        jtf_confirmarContrasenia1.setBackground(new java.awt.Color(187, 186, 186));
        jtf_confirmarContrasenia1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtf_confirmarContrasenia1.setForeground(new java.awt.Color(51, 51, 51));
        jf_registro1.getContentPane().add(jtf_confirmarContrasenia1, java.awt.BorderLayout.PAGE_START);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Confirmar contraseña: ");
        jf_registro1.getContentPane().add(jLabel21, java.awt.BorderLayout.PAGE_END);

        jtf_contraseniaRegistro1.setBackground(new java.awt.Color(187, 186, 186));
        jtf_contraseniaRegistro1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtf_contraseniaRegistro1.setForeground(new java.awt.Color(51, 51, 51));
        jf_registro1.getContentPane().add(jtf_contraseniaRegistro1, java.awt.BorderLayout.LINE_END);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Contraseña: ");
        jf_registro1.getContentPane().add(jLabel22, java.awt.BorderLayout.LINE_START);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Usuario:");
        jf_registro1.getContentPane().add(jLabel23, java.awt.BorderLayout.CENTER);

        jtf_usuarioRegistro1.setBackground(new java.awt.Color(187, 186, 186));
        jtf_usuarioRegistro1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtf_usuarioRegistro1.setForeground(new java.awt.Color(51, 51, 51));
        jf_registro1.getContentPane().add(jtf_usuarioRegistro1, java.awt.BorderLayout.CENTER);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Nombre completo: ");
        jf_registro1.getContentPane().add(jLabel24, java.awt.BorderLayout.CENTER);

        jtf_nombreRegistro1.setBackground(new java.awt.Color(187, 186, 186));
        jtf_nombreRegistro1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtf_nombreRegistro1.setForeground(new java.awt.Color(51, 51, 51));
        jf_registro1.getContentPane().add(jtf_nombreRegistro1, java.awt.BorderLayout.CENTER);

        jl_bg4.setBackground(new java.awt.Color(204, 204, 204));
        jl_bg4.setOpaque(true);
        jf_registro1.getContentPane().add(jl_bg4, java.awt.BorderLayout.CENTER);

        jSeparator4.setBackground(new java.awt.Color(208, 92, 95));
        jSeparator4.setOpaque(true);
        jf_registro1.getContentPane().add(jSeparator4, java.awt.BorderLayout.CENTER);

        jLabel25.setBackground(new java.awt.Color(58, 91, 123));
        jLabel25.setOpaque(true);
        jf_registro1.getContentPane().add(jLabel25, java.awt.BorderLayout.CENTER);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setText("LOG IN");
        jf_registro1.getContentPane().add(jLabel26, java.awt.BorderLayout.CENTER);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/unitec.jpg"))); // NOI18N
        jf_registro1.getContentPane().add(jLabel27, java.awt.BorderLayout.CENTER);

        jb_registro2.setBackground(new java.awt.Color(169, 169, 169));
        jb_registro2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb_registro2.setForeground(new java.awt.Color(51, 51, 51));
        jb_registro2.setText("Registro");
        jf_login2.getContentPane().add(jb_registro2, java.awt.BorderLayout.CENTER);

        jb_ingresar2.setBackground(new java.awt.Color(169, 169, 169));
        jb_ingresar2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb_ingresar2.setForeground(new java.awt.Color(51, 51, 51));
        jb_ingresar2.setText("Ingresar");
        jf_login2.getContentPane().add(jb_ingresar2, java.awt.BorderLayout.PAGE_START);

        jl_bg5.setBackground(new java.awt.Color(204, 204, 204));
        jl_bg5.setOpaque(true);
        jf_login2.getContentPane().add(jl_bg5, java.awt.BorderLayout.PAGE_END);

        jtf_contraseniaLogin2.setBackground(new java.awt.Color(187, 186, 186));
        jtf_contraseniaLogin2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtf_contraseniaLogin2.setForeground(new java.awt.Color(51, 51, 51));
        jf_login2.getContentPane().add(jtf_contraseniaLogin2, java.awt.BorderLayout.LINE_END);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Contraseña: ");
        jf_login2.getContentPane().add(jLabel28, java.awt.BorderLayout.LINE_START);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Usuario: ");
        jf_login2.getContentPane().add(jLabel29, java.awt.BorderLayout.CENTER);

        jtf_usuarioLogin2.setBackground(new java.awt.Color(187, 186, 186));
        jtf_usuarioLogin2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtf_usuarioLogin2.setForeground(new java.awt.Color(51, 51, 51));
        jf_login2.getContentPane().add(jtf_usuarioLogin2, java.awt.BorderLayout.CENTER);

        jSeparator6.setBackground(new java.awt.Color(208, 92, 95));
        jSeparator6.setOpaque(true);
        jf_login2.getContentPane().add(jSeparator6, java.awt.BorderLayout.CENTER);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel30.setText("LOG IN");
        jf_login2.getContentPane().add(jLabel30, java.awt.BorderLayout.CENTER);

        jLabel31.setBackground(new java.awt.Color(58, 91, 123));
        jLabel31.setOpaque(true);
        jf_login2.getContentPane().add(jLabel31, java.awt.BorderLayout.CENTER);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/unitec.jpg"))); // NOI18N
        jf_login2.getContentPane().add(jLabel32, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton jb_ingresar2;
    private javax.swing.JButton jb_registrarse1;
    private javax.swing.JButton jb_registro2;
    private javax.swing.JFrame jf_login2;
    private javax.swing.JFrame jf_registro1;
    private javax.swing.JLabel jl_bg4;
    private javax.swing.JLabel jl_bg5;
    private javax.swing.JTextField jtf_confirmarContrasenia1;
    private javax.swing.JTextField jtf_contraseniaLogin2;
    private javax.swing.JTextField jtf_contraseniaRegistro1;
    private javax.swing.JTextField jtf_nombreRegistro1;
    private javax.swing.JTextField jtf_usuarioLogin2;
    private javax.swing.JTextField jtf_usuarioRegistro1;
    // End of variables declaration//GEN-END:variables
Thread hilo;
}
